/*********************************************************************
 *                                                                    *
 *                SEGGER Microcontroller GmbH & Co. KG                *
 *        Solutions for real time microcontroller applications        *
 *                                                                    *
 **********************************************************************
 *                                                                    *
 * C-file generated by:                                               *
 *                                                                    *
 *        GUI_Builder for emWin version 5.28                          *
 *        Compiled Jan 30 2015, 16:41:06                              *
 *        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
 *                                                                    *
 **********************************************************************
 *                                                                    *
 *        Internet: www.segger.com  Support: support@segger.com       *
 *                                                                    *
 **********************************************************************
 */

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "led.h"
#include "pwmout.h"

pwmout_struct pwmout_config = {
    0,
    0,
    0,
    0,
    0,
};
u32 slider_value;

/*********************************************************************
 *
 *       Defines
 *
 **********************************************************************
 */
#define ID_FRAMEWIN_0 (GUI_ID_USER + 0x0B)
#define ID_BUTTON_0 (GUI_ID_USER + 0x0C)
#define ID_CHECKBOX_0 (GUI_ID_USER + 0x0E)
#define ID_SLIDER_0 (GUI_ID_USER + 0x10)
#define ID_TEXT_0 (GUI_ID_USER + 0x11)
#define ID_TEXT_1 (GUI_ID_USER + 0x12)
#define ID_TEXT_2 (GUI_ID_USER + 0x13)
#define ID_CHECKBOX_1 (GUI_ID_USER + 0x14)
#define ID_LISTBOX_0 (GUI_ID_USER + 0x17)

// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
 *
 *       Static data
 *
 **********************************************************************
 */

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
 *
 *       _aDialogCreate
 */
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
    {FRAMEWIN_CreateIndirect, "Motor_Controller", ID_FRAMEWIN_0, 0, 0, 800, 480, 0, 0x64, 0},
    {BUTTON_CreateIndirect, "PWM_Gen", ID_BUTTON_0, 326, 309, 100, 45, 0, 0x0, 0},
    {CHECKBOX_CreateIndirect, "Right_Motor", ID_CHECKBOX_0, 343, 167, 88, 20, 0, 0x0, 0},
    {SLIDER_CreateIndirect, "Slider", ID_SLIDER_0, 311, 248, 121, 32, 0, 0x0, 0},
    {TEXT_CreateIndirect, "Speed", ID_TEXT_0, 349, 278, 80, 20, 0, 0x0, 0},
    {TEXT_CreateIndirect, "Faster", ID_TEXT_1, 446, 258, 80, 20, 0, 0x0, 0},
    {TEXT_CreateIndirect, "Slower", ID_TEXT_2, 274, 257, 31, 20, 0, 0x0, 0},
    {CHECKBOX_CreateIndirect, "Left_Motor", ID_CHECKBOX_1, 343, 204, 80, 20, 0, 0x0, 0},
    {LISTBOX_CreateIndirect, "Listbox", ID_LISTBOX_0, 307, 82, 138, 53, 0, 0x0, 0},
    // USER START (Optionally insert additional widgets)
    // USER END
};

/*********************************************************************
 *
 *       Static code
 *
 **********************************************************************
 */

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
 *
 *       _cbDialog
 */
static void _cbDialog(WM_MESSAGE *pMsg)
{
    WM_HWIN hItem;
    int NCode;
    int Id;
    // USER START (Optionally insert additional variables)
    // USER END

    switch (pMsg->MsgId)
    {
    case WM_INIT_DIALOG:
        //
        // Initialization of 'Motor_Controller'
        //
        hItem = pMsg->hWin;
        FRAMEWIN_SetFont(hItem, GUI_FONT_32B_ASCII);
        FRAMEWIN_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
        FRAMEWIN_SetText(hItem, "Motor_Controller");
        //
        // Initialization of 'Right_Motor'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_0);
        CHECKBOX_SetText(hItem, "Right_Motor");
        //
        // Initialization of 'Speed'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
        TEXT_SetFont(hItem, GUI_FONT_16B_ASCII);
        //
        // Initialization of 'Left_Motor'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_1);
        CHECKBOX_SetText(hItem, "Left_Motor");
        //
        // Initialization of 'Listbox'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_0);
        LISTBOX_AddString(hItem, "Clockwise");
        LISTBOX_AddString(hItem, "Counter_Clockwise");
        LISTBOX_SetFont(hItem, GUI_FONT_16_1HK);
        // USER START (Optionally insert additional code for further widget initialization)
        // USER END
        break;
    case WM_NOTIFY_PARENT:
        Id = WM_GetId(pMsg->hWinSrc);
        NCode = pMsg->Data.v;
        switch (Id)
        {
        case ID_BUTTON_0: //! Notifications sent by 'PWM_Gen'
            switch (NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
            case WM_NOTIFICATION_RELEASED:
            {
                //! PWM_GEN按键
                //! 按下后发波，LED1（绿灯）亮
                //! 再次按下停止发波，LED0（红灯）亮

                if (pwmout_config.pwm_enable == 0)
                {
                    PWM_Gen(pwmout_config);
                    LED0(1);
                    LED1(0);
                    pwmout_config.pwm_enable = 1;
                }
                else
                {
                    PWM_Stop();
                    LED0(0);
                    LED1(1);
                    pwmout_config.pwm_enable = 0;
                }
                //! USER END
                break;
            }

                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;
        case ID_CHECKBOX_0: //! Notifications sent by 'Right_Motor'
            switch (NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
            case WM_NOTIFICATION_RELEASED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
            case WM_NOTIFICATION_VALUE_CHANGED:
            {
                //! 当checkbox "Right_Motor"的状态改变时：
                hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_0);

                if (CHECKBOX_IsChecked(hItem))
                {
                    LED1(0);
                    pwmout_config.right_motor = 1;
                }
                else
                {
                    LED1(1);
                    pwmout_config.right_motor = 1;
                }

                //! USER END
                break;
            }
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;
        case ID_SLIDER_0: //! Notifications sent by 'Slider'
            switch (NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
            case WM_NOTIFICATION_RELEASED:

                //! 当Slider的值发生改变的时候
                hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_0);
                slider_value = SLIDER_GetValue(hItem);
                
                printf("\r\nspeed is: %u .\r\n", slider_value);
                pwmout_config.speed = slider_value;
                //! USER END
                
                break;
            case WM_NOTIFICATION_VALUE_CHANGED:
                
                break;
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;
        case ID_CHECKBOX_1: // Notifications sent by 'Left_Motor'
            switch (NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
            case WM_NOTIFICATION_RELEASED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
            case WM_NOTIFICATION_VALUE_CHANGED:
            {
                //! 当checkbox "Right_Motor"的状态改变时：
                hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_1);

                if (CHECKBOX_IsChecked(hItem))
                {
                    LED0(0);
                    pwmout_config.left_motor = 1;
                }
                else
                {
                    LED0(1);
                    pwmout_config.left_motor = 1;
                }

                //! USER END
                break;
            }
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;
        case ID_LISTBOX_0: // Notifications sent by 'Listbox'
            switch (NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
            case WM_NOTIFICATION_RELEASED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                //! 当正反转的状态改变时：
                hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_0);

                if (LISTBOX_GetSel(hItem) == 0)  //! 顺时针
                {
                    LED0(1);
                    LED1(0);
                    pwmout_config.rotate_direction = 0;
                }   
                else if(LISTBOX_GetSel(hItem) == 1) //! 逆时针
                {
                    LED0(0);
                    LED1(1);
                    pwmout_config.rotate_direction = 1;
                } 

                //! USER END
                break;
            case WM_NOTIFICATION_SEL_CHANGED:
            {

                break;
            }
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;
            // USER START (Optionally insert additional code for further Ids)
            // USER END
        }
        break;
        // USER START (Optionally insert additional message handling)
        // USER END
    default:
        WM_DefaultProc(pMsg);
        break;
    }
}

/*********************************************************************
 *
 *       Public code
 *
 **********************************************************************
 */
/*********************************************************************
 *
 *       CreateMotor_Controller
 */
WM_HWIN CreateMotor_Controller(void);
WM_HWIN CreateMotor_Controller(void)
{
    WM_HWIN hWin;

    hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
    return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/

void MainTask(void)
{
    /* ?????????? */
    WM_SetCreateFlags(WM_CF_MEMDEV);
    /* ??? */
    GUI_Init();
    /* ?????,?? GUIBulder5.28 ?????????? */
    CreateMotor_Controller();
    while (1)
    {
        GUI_Delay(10);
        //printf("\r\nmessage sent!\r\n");
    }
}
/*************************** End of file ****************************/
/*************************** End of file ****************************/
